# Generated by Django 2.2.3 on 2019-08-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_farejando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
